# Generated by Django 6.0 on 2025-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
